spring.application.name=negosyopro
spring.datasource.url=jdbc:mysql://localhost:3306/negosyopro_inventory
spring.datasource.username=negosyopro-inventory
spring.datasource.password=OopInventorySystem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true